server:
  port: 4000
spring:
  application:
    name: omnisystem
  datasource:
    url: jdbc:postgresql://localhost:5432/pinsoft
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
